service: jp-flashcards-2
frameworkVersion: '3'

plugins:
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}

custom:
  service: '${self:service}'
  stage: '${self:provider.stage}'
  bucket: '${env:BUCKET_NAME, self:custom.service}-${self:custom.stage}'
  table: '${env:TABLE_NAME, self:custom.service}-${self:custom.stage}'
  s3:
    host: localhost
    directory: assets
    port: 4569
  s3local:
    host: ${self:custom.s3.host}
    port: ${self:custom.s3.port}
    cors: '*'
    imageUpload: true
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      convertEmptyValues: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:custom.table}
            sources: [offline/migrations/flashcards-seed.json]

  iam:
    role:
      name: ${self:service}-${self:provider.stage}-role
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - "arn:aws:s3:::${self:custom.bucket}/*"
      # - Effect: Allow
      #   Action:
      #     - dynamodb:Query
      #     - dynamodb:Scan
      #   Resource:
      #     - Fn::GetAtt: [ UsersTable, Arn ]

resources:
  Resources:
    FlashcardsAssets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName:
          Fn::Sub: ${self:custom.bucket}

    FlashcardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1-PK
            AttributeType: S
          - AttributeName: GSI1-SK
            AttributeType: S
          - AttributeName: GSI2-PK
            AttributeType: S
          - AttributeName: GSI2-SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1-PK
                KeyType: HASH
              - AttributeName: GSI1-SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: GSI2
            KeySchema:
              - AttributeName: GSI2-PK
                KeyType: HASH
              - AttributeName: GSI2-SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1