service: jp-flashcards-2
frameworkVersion: '3'

plugins:
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  environment:
    tableName: { Ref: FlashcardsTable }

custom:
  service: ${self:service}
  stage: ${self:provider.stage}
  s3:
    host: localhost
    directory: assets
    port: 4569
  s3local:
    host: ${self:custom.s3.host}
    port: ${self:custom.s3.port}
    cors: '*'
    imageUpload: true
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      convertEmptyValues: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: '${self:custom.service}-${self:custom.stage}'
            sources: [offline/migrations/flashcards-seed.json]
    dynamodbSeed:
      sources:
        - table: '${self:custom.service}-${self:custom.stage}'
          sources: [offline/migrations/flashcards-seed.json]

resources:
  Resources:
    FlashcardsAssets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName:
          Fn::Sub: '${self:custom.service}-${self:custom.stage}'

    FlashcardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:custom.service}-${self:custom.stage}'
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1-PK
            AttributeType: S
          - AttributeName: GSI1-SK
            AttributeType: S
          - AttributeName: GSI2-PK
            AttributeType: S
          - AttributeName: GSI2-SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1-PK
                KeyType: HASH
              - AttributeName: GSI1-SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: GSI2
            KeySchema:
              - AttributeName: GSI2-PK
                KeyType: HASH
              - AttributeName: GSI2-SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1